<?php

/**
 * This is the model base class for the table "company_users".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CompanyUsers".
 *
 * Columns in table "company_users" available as properties of the model,
 * followed by relations of table "company_users" available as properties of the model.
 *
 * @property integer $idcompany_users
 * @property integer $idcompanies
 * @property integer $idusers
 *
 * @property Companies $idcompanies0
 * @property Users $idusers0
 */
abstract class BaseCompanyUsers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'company_users';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CompanyUsers|CompanyUsers', $n);
	}

	public static function representingColumn() {
		return 'idcompany_users';
	}

	public function rules() {
		return array(
			array('idcompanies, idusers', 'numerical', 'integerOnly'=>true),
			array('idcompanies, idusers', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idcompany_users, idcompanies, idusers', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idcompanies0' => array(self::BELONGS_TO, 'Companies', 'idcompanies'),
			'idusers0' => array(self::BELONGS_TO, 'Users', 'idusers'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idcompany_users' => Yii::t('app', 'Idcompany Users'),
			'idcompanies' => null,
			'idusers' => null,
			'idcompanies0' => null,
			'idusers0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idcompany_users', $this->idcompany_users);
		$criteria->compare('idcompanies', $this->idcompanies);
		$criteria->compare('idusers', $this->idusers);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}