<?php

/**
 * This is the model base class for the table "jobs_applied".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "JobsApplied".
 *
 * Columns in table "jobs_applied" available as properties of the model,
 * followed by relations of table "jobs_applied" available as properties of the model.
 *
 * @property integer $idjobsapplied
 * @property integer $idjobs
 * @property integer $idusers
 * @property string $cdate
 * @property string $mdate
 *
 * @property JobInvites[] $jobInvites
 * @property Jobs $idjobs0
 * @property Users $idusers0
 */
abstract class BaseJobsApplied extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'jobs_applied';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'JobsApplied|JobsApplieds', $n);
	}

	public static function representingColumn() {
		return 'cdate';
	}

	public function rules() {
		return array(
			array('idjobs, idusers', 'numerical', 'integerOnly'=>true),
			array('cdate, mdate', 'length', 'max'=>45),
			array('idjobs, idusers, cdate, mdate', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idjobsapplied, idjobs, idusers, cdate, mdate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'jobInvites' => array(self::HAS_MANY, 'JobInvites', 'idjobsapplied'),
			'idjobs0' => array(self::BELONGS_TO, 'Jobs', 'idjobs'),
			'idusers0' => array(self::BELONGS_TO, 'Users', 'idusers'),//add by deependra
                        //'idjobmessage'=> array(self::HAS_MANY,'JobMessages','');
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idjobsapplied' => Yii::t('app', 'Idjobsapplied'),
			'idjobs' => null,
			'idusers' => null,
			'cdate' => Yii::t('app', 'Cdate'),
			'mdate' => Yii::t('app', 'Mdate'),
			'jobInvites' => null,
			'idjobs0' => null,
			'idusers0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idjobsapplied', $this->idjobsapplied);
		$criteria->compare('idjobs', $this->idjobs);
		$criteria->compare('idusers', $this->idusers);
		$criteria->compare('cdate', $this->cdate, true);
		$criteria->compare('mdate', $this->mdate, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}