<?php

/**
 * This is the model base class for the table "job_terms".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "JobTerms".
 *
 * Columns in table "job_terms" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idjobterms
 * @property integer $idjobs
 * @property integer $idterms
 *
 */
abstract class BaseJobTerms extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'job_terms';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'JobTerms|JobTerms', $n);
	}

	public static function representingColumn() {
		return 'idjobterms';
	}

	public function rules() {
		return array(
			array('idjobs, idterms', 'required'),
			array('idjobs, idterms', 'numerical', 'integerOnly'=>true),
			array('idjobterms, idjobs, idterms', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
                    'idjobs0'=>array(self::BELONGS_TO,'Jobs','idjobs'),
                    'idterms0'=>array(self::BELONGS_TO,'Terms','idterms'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idjobterms' => Yii::t('app', 'Idjobterms'),
			'idjobs' => Yii::t('app', 'Idjobs'),
			'idterms' => Yii::t('app', 'Idterms'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idjobterms', $this->idjobterms);
		$criteria->compare('idjobs', $this->idjobs);
		$criteria->compare('idterms', $this->idterms);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
        
}