<?php

/**
 * This is the model base class for the table "user_edu".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserEdu".
 *
 * Columns in table "user_edu" available as properties of the model,
 * followed by relations of table "user_edu" available as properties of the model.
 *
 * @property integer $idedu
 * @property integer $idusers
 * @property string $name
 * @property string $degree
 * @property string $completed
 * @property integer $ongoing
 * @property string $description
 * @property string $cdate
 * @property string $mdate
 *
 * @property Users $idusers0
 */
abstract class BaseUserEdu extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_edu';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserEdu|UserEdus', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('idusers, ongoing', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>128),
			array('degree', 'length', 'max'=>64),
			array('completed, description, cdate, mdate', 'safe'),
			array('name, degree, completed, ongoing, description, cdate, mdate', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idedu, idusers, name, degree, completed, ongoing, description, cdate, mdate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idusers0' => array(self::BELONGS_TO, 'Users', 'idusers'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idedu' => Yii::t('app', 'Idedu'),
			'idusers' => null,
			'name' => Yii::t('app', 'Name'),
			'degree' => Yii::t('app', 'Degree'),
			'completed' => Yii::t('app', 'Completed'),
			'ongoing' => Yii::t('app', 'Ongoing'),
			'description' => Yii::t('app', 'Description'),
			'cdate' => Yii::t('app', 'Cdate'),
			'mdate' => Yii::t('app', 'Mdate'),
			'idusers0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idedu', $this->idedu);
		$criteria->compare('idusers', $this->idusers);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('degree', $this->degree, true);
		$criteria->compare('completed', $this->completed, true);
		$criteria->compare('ongoing', $this->ongoing);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('cdate', $this->cdate, true);
		$criteria->compare('mdate', $this->mdate, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}