<?php

/**
 * This is the model base class for the table "companies".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Companies".
 *
 * Columns in table "companies" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idcompanies
 * @property string $name
 * @property string $url
 * @property string $country
 * @property string $description
 * @property string $state
 * @property string $city
 * @property string $address
 * @property integer $pin
 * @property string $phone
 * @property string $person
 *
 */
abstract class BaseCompanies extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'companies';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Companies|Companies', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name,state,pin', 'required'),
			array('pin', 'numerical', 'integerOnly'=>true),
			array('name, url, person', 'length', 'max'=>128),
			array('country, state, city', 'length', 'max'=>45),
			array('address', 'length', 'max'=>1028),
			array('phone', 'length', 'max'=>16),
			array('description', 'safe'),
			//array('name, url, country, description, state, city, address, pin, phone, person', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idcompanies, name, url, country, description, state, city, address, pin, phone, person', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
                    'idcompany0' => array(self::HAS_MANY, 'Companies', 'idcompanies'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idcompanies' => Yii::t('app', 'Idcompanies'),
			'name' => Yii::t('app', 'Name'),
			'url' => Yii::t('app', 'Url'),
			'country' => Yii::t('app', 'Country'),
			'description' => Yii::t('app', 'Description'),
			'state' => Yii::t('app', 'State'),
			'city' => Yii::t('app', 'City'),
			'address' => Yii::t('app', 'Address'),
			'pin' => Yii::t('app', 'Pin'),
			'phone' => Yii::t('app', 'Phone'),
			'person' => Yii::t('app', 'Person'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idcompanies', $this->idcompanies);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('country', $this->country, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('state', $this->state, true);
		$criteria->compare('city', $this->city, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('pin', $this->pin);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('person', $this->person, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}