<?php

/**
 * This is the model base class for the table "company_meta".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CompanyMeta".
 *
 * Columns in table "company_meta" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idcompanymeta
 * @property integer $idcompany
 * @property string $meta_name
 * @property string $meta_value
 *
 */
abstract class BaseCompanyMeta extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'company_meta';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CompanyMeta|CompanyMetas', $n);
	}

	public static function representingColumn() {
		return 'meta_name';
	}

	public function rules() {
		return array(
			array('idcompany, meta_name', 'required'),
			array('idcompany', 'numerical', 'integerOnly'=>true),
			array('meta_name', 'length', 'max'=>64),
			array('meta_value', 'length', 'max'=>2048),
			array('meta_value', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idcompanymeta, idcompany, meta_name, meta_value', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
                   
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idcompanymeta' => Yii::t('app', 'Idcompanymeta'),
			'idcompany' => Yii::t('app', 'Idcompany'),
			'meta_name' => Yii::t('app', 'Meta Name'),
			'meta_value' => Yii::t('app', 'Meta Value'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idcompanymeta', $this->idcompanymeta);
		$criteria->compare('idcompany', $this->idcompany);
		$criteria->compare('meta_name', $this->meta_name, true);
		$criteria->compare('meta_value', $this->meta_value, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}