<?php

/**
 * This is the model base class for the table "users".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Users".
 *
 * Columns in table "users" available as properties of the model,
 * followed by relations of table "users" available as properties of the model.
 *
 * @property integer $idusers
 * @property string $username
 * @property string $email
 * @property string $password
 * @property string $cdate
 * @property string $mdate
 * @property string $activkey
 * @property integer $type
 * @property integer $status
 *
 * @property CompanyUsers[] $companyUsers
 * @property JobsApplied[] $jobsApplieds
 * @property UserEdu[] $userEdus
 * @property UserExp[] $userExps
 * @property UserProfile[] $userProfiles
 */
class UserOnline extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'users';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserOnline|UserOnline', $n);
	}

	public static function representingColumn() {
		return 'username';
	}

	public function rules() {
		return array(
                        array('idusers,last_activity, username, email, password, cdate, mdate, activkey, type, status', 'safe', 'on'=>'search'),
		
		);
	}

//	public function relations() {
//		return array(
//			'companyUsers' => array(self::HAS_MANY, 'CompanyUsers', 'idusers'),
//			'jobsApplieds' => array(self::HAS_MANY, 'JobsApplied', 'idusers'),
//			'userEdus' => array(self::HAS_MANY, 'UserEdu', 'idusers'),
//			'userExps' => array(self::HAS_MANY, 'UserExp', 'idusers'),
//			'userProfiles' => array(self::HAS_MANY, 'UserProfile', 'idusers'),
//                        'userProfiles0' => array(self::HAS_ONE, 'UserProfile', 'idusers'),
//                        //'company' => array(self::HAS_ONE, 'UserProfile', 'idusers'),
//		);
//	}

	public function attributeLabels() {
		return array(
			'idusers' => Yii::t('app', 'Idusers'),
			'username' => Yii::t('app', 'Username'),
			'email' => Yii::t('app', 'Email'),
			'password' => Yii::t('app', 'Password'),
			'cdate' => Yii::t('app', 'Cdate'),
			'mdate' => Yii::t('app', 'Mdate'),
			'activkey' => Yii::t('app', 'Activkey'),
			'type' => Yii::t('app', 'Type'),
			'status' => Yii::t('app', 'Status'),
			'companyUsers' => null,
			'jobsApplieds' => null,
			'userEdus' => null,
			'userExps' => null,
			'userProfiles' => null,
		);
	}

}
